### ISSUE TITLE
sportsMOT验证报错： Uploaded results are not one-to-one matches to the test set.

### ISSUE THREAD

**Issue by congyao123456** [MCG-NJU/SportsMOT#10]
你好，压缩文件夹下一共150个.txt文件上传到sportsMOT出现：
Traceback (most recent call last):
File "/tmp/codalab/tmpxw6bI2/run/program/evaluate_full_test.py", line 22, in
organize_input_full.process(input_dir)
File "/tmp/codalab/tmpxw6bI2/run/program/organize_input_full.py", line 63, in process
"Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.
请问问题在哪，期待您的回复，不胜感激

**Comment by goldentimecoolk** [comment]
我也遇到了同样的问题，请问你解决了吗？

-------------

问题已解决：
直接对txt压缩，不要对txt的文件夹压缩
