### ISSUE TITLE
Problem of submitting the result to the evaluation server on Codalab

### ISSUE THREAD

**Issue by Qweqwem3m3m3** [MCG-NJU/SportsMOT#17]
Dear Author, I am highly interset in SportsMOT dataset, I have participated in the competition on the codalab recently. I am familiar with the rules of the submission that one account can only submit one result per day. To submit, I have to upload a .zip file containing text files with the prediction. But I encounter a problem while submitting my result. I have tried to upload my result zip file several days. Still failed to upload it on to Codalab competition.  I really need your help！

Thank in advance.

**Comment by Qweqwem3m3m3** [comment]
I encountered a new problem, I uploaded my results on the Codalab several times, and always failed.
The message I got is at below:
Traceback (most recent call last):
  File "/tmp/codalab/tmpyhjAcb/run/program/evaluate_full_test.py", line 22, in 
    organize_input_full.process(input_dir)
  File "/tmp/codalab/tmpyhjAcb/run/program/organize_input_full.py", line 63, in process
    "Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.

I checked the zip file I created and it contains exactly 150 txt outputs, ran from the test set of SportsMOT.

**Comment by jinho88** [comment]
Did you figure out this problem?
I have the same problem.
I can find result txt which is indicated "not found" in the output log.
